name: gomu
adopt-info: gomu
summary: Gomu is intuitive, powerful CLI music player.
description: |
  Gomu is intuitive, powerful CLI music player. 
  It has embedded scripting language and event hook to enable user to 
  customize their config extensively.
    
license: GPL-2.0

base: core20
grade: stable 
confinement: strict
compression: lzo

assumes:
  - command-chain
  
apps:
  gomu:
    command: $SNAP/.local/bin/gomu
    command-chain: 
      - bin/homeishome-launch     
    plugs:
      - home
      - network
      - network-bind
      - audio-playback
parts:
  gomu:
    source: https://github.com/issadarkthing/gomu
    source-type: git
    plugin: go
    build-snaps:
      - go
    build-packages:
      - libasound2-dev
      - youtube-dl
      - pkg-config
    stage-packages:
      - libasound
      
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
        
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch     
